/**
 * CompletionMessageTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class CompletionMessageTool : CompletionMessage
{
    [JsonPropertyName("tool_call_id")]
    public string? ToolCallId { get; set; }

}

