/**
 * CompletionMessageUser automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class CompletionMessageUser : CompletionMessage
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

}

