/**
 * ResponseRequestText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseRequestText
{
    [JsonPropertyName("format")]
    public ResponseRequestTextFormat? Format { get; set; }

    [JsonPropertyName("verbosity")]
    public string? Verbosity { get; set; }

}

