/**
 * ResponsePrompt automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponsePrompt
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("variables")]
    public System.Collections.Generic.Dictionary<string, string>? Variables { get; set; }

    [JsonPropertyName("version")]
    public string? Version { get; set; }

}

