/**
 * ResponseRequestTextFormat automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseRequestTextFormatJsonSchema), typeDiscriminator: "json_schema")]
[JsonDerivedType(typeof(ResponseRequestTextFormatText), typeDiscriminator: "text")]
public abstract class ResponseRequestTextFormat
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

