/**
 * ResponseToolWebSearch automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseToolWebSearch : ResponseTool
{
    [JsonPropertyName("type")]
    public new string? Type { get; set; }

    [JsonPropertyName("filters")]
    public ResponseToolWebSearchFilter? Filters { get; set; }

    [JsonPropertyName("search_context_size")]
    public string? SearchContextSize { get; set; }

    [JsonPropertyName("user_location")]
    public ResponseToolWebSearchLocation? UserLocation { get; set; }

}

