/**
 * ResponseRequestInputMcpListTools automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

/// <summary>
/// A list of tools available on an MCP server.
/// </summary>
public class ResponseRequestInputMcpListTools : ResponseRequestInput
{
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("server_label")]
    public string? ServerLabel { get; set; }

    [JsonPropertyName("tools")]
    public System.Collections.Generic.List<ResponseMCPTool>? Tools { get; set; }

    [JsonPropertyName("error")]
    public string? Error { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "mcp_list_tools";

}

