/**
 * ResponseResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseResponse
{
    [JsonPropertyName("created_at")]
    public int? CreatedAt { get; set; }

    [JsonPropertyName("error")]
    public ResponseResponseError? Error { get; set; }

    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("incomplete_details")]
    public string? IncompleteDetails { get; set; }

    [JsonPropertyName("object")]
    public string? Object { get; set; } = "response";

    [JsonPropertyName("output")]
    public System.Collections.Generic.List<ResponseResponseOutput>? Output { get; set; }

    [JsonPropertyName("previous_response_id")]
    public string? PreviousResponseId { get; set; }

}

