/**
 * ResponseReasoning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseReasoning
{
    [JsonPropertyName("effort")]
    public string? Effort { get; set; }

    [JsonPropertyName("summary")]
    public string? Summary { get; set; }

}

