/**
 * ResponseResponseOutputMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

/// <summary>
/// An output message from the model.
/// </summary>
public class ResponseResponseOutputMessage : ResponseResponseOutput
{
    [JsonPropertyName("content")]
    public System.Collections.Generic.List<string>? Content { get; set; }

    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("role")]
    public string? Role { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "message";

}

