/**
 * ResponseToolMCP automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseToolMCP : ResponseTool
{
    [JsonPropertyName("server_label")]
    public string? ServerLabel { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; }

    [JsonPropertyName("allowed_tools")]
    public System.Collections.Generic.List<string>? AllowedTools { get; set; }

    [JsonPropertyName("authorization")]
    public string? Authorization { get; set; }

    [JsonPropertyName("connector_id")]
    public string? ConnectorId { get; set; }

    [JsonPropertyName("headers")]
    public System.Collections.Generic.Dictionary<string, string>? Headers { get; set; }

    [JsonPropertyName("require_approval")]
    public string? RequireApproval { get; set; }

    [JsonPropertyName("server_description")]
    public string? ServerDescription { get; set; }

    [JsonPropertyName("server_url")]
    public string? ServerUrl { get; set; }

}

