/**
 * ResponseRequestInputFunctionCallOutput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

/// <summary>
/// The output of a function tool call.
/// </summary>
public class ResponseRequestInputFunctionCallOutput : ResponseRequestInput
{
    [JsonPropertyName("call_id")]
    public string? CallId { get; set; }

    [JsonPropertyName("output")]
    public string? Output { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "function_call_output";

    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

}

