/**
 * ResponseTextFormat automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseTextFormatJsonSchema), typeDiscriminator: "json_schema")]
[JsonDerivedType(typeof(ResponseTextFormatText), typeDiscriminator: "text")]
public abstract class ResponseTextFormat
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

