/**
 * ResponseRequestInput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

/// <summary>
/// An item representing part of the context for the response to be generated by the model. Can contain text, images, and audio inputs, as well as previous assistant responses and tool call outputs.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseRequestInputFunctionCall), typeDiscriminator: "function_call")]
[JsonDerivedType(typeof(ResponseRequestInputFunctionCallOutput), typeDiscriminator: "function_call_output")]
[JsonDerivedType(typeof(ResponseRequestInputMessage), typeDiscriminator: "message")]
public abstract class ResponseRequestInput
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

