/**
 * ResponseTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseToolFunction), typeDiscriminator: "function")]
[JsonDerivedType(typeof(ResponseToolMCP), typeDiscriminator: "mcp")]
[JsonDerivedType(typeof(ResponseToolWebSearch), typeDiscriminator: "web_search")]
public abstract class ResponseTool
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

