/**
 * ResponseRequestTextFormatJsonSchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseRequestTextFormatJsonSchema : ResponseRequestTextFormat
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("schema")]
    public object? Schema { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "json_schema";

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    [JsonPropertyName("strict")]
    public bool? Strict { get; set; }

}

