/**
 * ResponseRequestTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseRequestToolFunction), typeDiscriminator: "function")]
public abstract class ResponseRequestTool
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

