/**
 * ResponseResponseOutput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(ResponseResponseOutputFunctionCall), typeDiscriminator: "function_call")]
[JsonDerivedType(typeof(ResponseResponseOutputMessage), typeDiscriminator: "message")]
public abstract class ResponseResponseOutput
{
    [JsonPropertyName("type")]
    public string? Type { get; set; }

}

