/**
 * ResponseToolWebSearchFilter automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseToolWebSearchFilter
{
    [JsonPropertyName("allowed_domains")]
    public System.Collections.Generic.List<string>? AllowedDomains { get; set; }

}

