/**
 * ResponseRequestInputFunctionCall automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

/// <summary>
/// A tool call to run a function. See the function calling guide for more information.
/// </summary>
public class ResponseRequestInputFunctionCall : ResponseRequestInput
{
    [JsonPropertyName("arguments")]
    public string? Arguments { get; set; }

    [JsonPropertyName("call_id")]
    public string? CallId { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "function_call";

    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

}

