/**
 * ResponseTextFormatText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseTextFormatText : ResponseTextFormat
{
    [JsonPropertyName("type")]
    public new string? Type { get; set; }

}

