/**
 * ResponseRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseRequest
{
    [JsonPropertyName("background")]
    public bool? Background { get; set; }

    [JsonPropertyName("conversation")]
    public ResponseRequestConversation? Conversation { get; set; }

    [JsonPropertyName("include")]
    public System.Collections.Generic.List<string>? Include { get; set; }

    [JsonPropertyName("input")]
    public string? Input { get; set; }

    [JsonPropertyName("instructions")]
    public string? Instructions { get; set; }

    [JsonPropertyName("max_output_tokens")]
    public string? MaxOutputTokens { get; set; }

    [JsonPropertyName("max_tool_calls")]
    public string? MaxToolCalls { get; set; }

    [JsonPropertyName("metadata")]
    public System.Collections.Generic.Dictionary<string, string>? Metadata { get; set; }

    [JsonPropertyName("model")]
    public string? Model { get; set; }

    [JsonPropertyName("parallel_tool_calls")]
    public bool? ParallelToolCalls { get; set; }

    [JsonPropertyName("previous_response_id")]
    public string? PreviousResponseId { get; set; }

    [JsonPropertyName("prompt")]
    public ResponsePrompt? Prompt { get; set; }

    [JsonPropertyName("prompt_cache_key")]
    public string? PromptCacheKey { get; set; }

    [JsonPropertyName("reasoning")]
    public ResponseReasoning? Reasoning { get; set; }

    [JsonPropertyName("safety_identifier")]
    public string? SafetyIdentifier { get; set; }

    [JsonPropertyName("service_tier")]
    public string? ServiceTier { get; set; }

    [JsonPropertyName("store")]
    public bool? Store { get; set; }

    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; }

    [JsonPropertyName("text")]
    public ResponseText? Text { get; set; }

    [JsonPropertyName("tool_choice")]
    public string? ToolChoice { get; set; }

    [JsonPropertyName("tools")]
    public System.Collections.Generic.List<ResponseTool>? Tools { get; set; }

    [JsonPropertyName("top_logprobs")]
    public int? TopLogprobs { get; set; }

    [JsonPropertyName("top_p")]
    public double? TopP { get; set; }

    [JsonPropertyName("truncation")]
    public string? Truncation { get; set; }

}

