/**
 * ResponseMCPTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseMCPTool
{
    [JsonPropertyName("input_schema")]
    public object? InputSchema { get; set; }

    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("annotations")]
    public System.Collections.Generic.Dictionary<string, string>? Annotations { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

}

