/**
 * ResponseText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseText
{
    [JsonPropertyName("format")]
    public ResponseTextFormat? Format { get; set; }

    [JsonPropertyName("verbosity")]
    public string? Verbosity { get; set; }

}

