/**
 * ResponseToolFunction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseToolFunction : ResponseTool
{
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    [JsonPropertyName("parameters")]
    public object? Parameters { get; set; }

    [JsonPropertyName("strict")]
    public bool? Strict { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "function";

    [JsonPropertyName("description")]
    public string? Description { get; set; }

}

