/**
 * ResponseRequestInputMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Openai;

public class ResponseRequestInputMessage : ResponseRequestInput
{
    [JsonPropertyName("content")]
    public System.Collections.Generic.List<string>? Content { get; set; }

    [JsonPropertyName("role")]
    public string? Role { get; set; }

    [JsonPropertyName("type")]
    public new string? Type { get; set; } = "message";

}

